export type NotificationEvent =
  | 'BORRADOR_CREADO'
  | 'RADICAR_SA'
  | 'SUBSANACION_SA'
  | 'DOC_COMPLETA_SA'
  | 'AVALADO_CF'
  | 'SUBSANACION_SG'
  | 'REENVIO_SUBSANACION_SG'
  | 'DOC_COMPLETA_SG'
  | 'DECISION_NO_APROBADA'
  | 'APROBACION_CA'
  | 'PENDIENTE_FECHAS'
  | 'INICIO_SABATICO';
